# Generated by Django 4.1.3 on 2022-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_meal_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="category",
            field=models.CharField(
                choices=[
                    ("Shawarma", "Shawarma"),
                    ("Burgers", "Burgers"),
                    ("Charcoal Grilled Chicken", "Charcoal Grilled Chicken"),
                    ("Rice", "Rice"),
                    ("Salads", "Salads"),
                    ("Sandwich", "Sandwich"),
                    ("Roasted Chicken", "Roasted Chicken"),
                    ("Fried Chicken", "Fried Chicken"),
                    ("Drinks", "Drinks"),
                    ("Smoothies", "Smoothies"),
                    ("Local Dish", "Local Dish"),
                ],
                default="Local Dish",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
