# Generated by Django 4.1.3 on 2022-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order_in_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
    ]
